const mealsDB = [
    // BREAKFAST
    {
        id: "b1",
        type: "Breakfast",
        title: "Avocado & Tofu Scramble Toast",
        desc: "High protein tofu scramble on whole grain bread with mashed avocado.",
        cals: 450,
        protein: 22,
        carbs: 45,
        fat: 20,
        weather: ["all"],
        festivals: [],
        countries: ["US", "UK", "AU", "CA"]
    },
    {
        id: "b2",
        type: "Breakfast",
        title: "Masala Poha with Peanuts & Edamame",
        desc: "Flattened rice cooked with onions, potatoes, peanuts, edamame, and turmeric.",
        cals: 400,
        protein: 20,
        carbs: 55,
        fat: 10,
        weather: ["all", "hot", "warm"],
        festivals: ["Diwali"],
        countries: ["IN"]
    },
    {
        id: "b3",
        type: "Breakfast",
        title: "Warm Apple Cinnamon Oatmeal",
        desc: "Comforting bowl of oats cooked with apple chunks, cinnamon, and walnuts.",
        cals: 380,
        protein: 10,
        carbs: 60,
        fat: 12,
        weather: ["cold", "cool"],
        festivals: ["Christmas", "Thanksgiving"],
        countries: ["US", "UK", "CA", "EU"]
    },
    {
        id: "b4",
        type: "Breakfast",
        title: "Idli Sambar",
        desc: "Steamed rice and lentil cakes served with a flavorful vegetable stew.",
        cals: 400,
        protein: 15,
        carbs: 65,
        fat: 5,
        weather: ["all"],
        festivals: ["Pongal"],
        countries: ["IN"]
    },
    {
        id: "b5",
        type: "Breakfast",
        title: "Chilaquiles Rojos",
        desc: "Tortilla chips simmered in red salsa, topped with avocado and vegan crema.",
        cals: 500,
        protein: 12,
        carbs: 60,
        fat: 25,
        weather: ["all"],
        festivals: ["Cinco de Mayo"],
        countries: ["MX", "US"]
    },
    {
        id: "b6",
        type: "Breakfast",
        title: "Full English Veggie Breakfast",
        desc: "Baked beans, grilled tomatoes, mushrooms, vegan sausages, and toast.",
        cals: 650,
        protein: 25,
        carbs: 70,
        fat: 30,
        weather: ["cold", "cool"],
        festivals: [],
        countries: ["UK", "IE"]
    },
    {
        id: "b7",
        type: "Breakfast",
        title: "High Protein Paneer-Stuffed Besan Chilla",
        desc: "Savory chickpea flour pancakes stuffed with spiced crumbled paneer.",
        cals: 380,
        protein: 24,
        carbs: 40,
        fat: 14,
        weather: ["all", "hot", "warm"],
        festivals: [],
        countries: ["IN"]
    },
    {
        id: "b8",
        type: "Breakfast",
        title: "Moong Dal Chilla",
        desc: "High protein lentil pancakes made from soaked moong dal and spices.",
        cals: 360,
        protein: 20,
        carbs: 45,
        fat: 10,
        weather: ["all"],
        festivals: [],
        countries: ["IN"]
    },
    {
        id: "b9",
        type: "Breakfast",
        title: "Paneer Paratha & Yogurt",
        desc: "Whole wheat flatbread stuffed with spiced paneer, served with a side of high-protein yogurt.",
        cals: 420,
        protein: 22,
        carbs: 50,
        fat: 16,
        weather: ["cold", "cool", "all"],
        festivals: [],
        countries: ["IN"]
    },
    {
        id: "b10",
        type: "Breakfast",
        title: "Peanut Butter & Banana Protein Pancakes",
        desc: "Kid-friendly whole wheat pancakes made with milk, topped with banana slices and peanut butter.",
        cals: 400,
        protein: 18,
        carbs: 55,
        fat: 16,
        weather: ["all", "cold", "cool"],
        festivals: [],
        countries: ["US", "UK", "CA", "AU", "IN", "EU"]
    },
    {
        id: "b11",
        type: "Breakfast",
        title: "Cheesy Paneer Veggie Roll",
        desc: "A fun, kid-friendly whole wheat wrap stuffed with hidden veggies, mild spices, and melted cheese with paneer.",
        cals: 380,
        protein: 16,
        carbs: 42,
        fat: 14,
        weather: ["all"],
        festivals: [],
        countries: ["IN", "US", "UK", "AU"]
    },

    // LUNCH
    {
        id: "l1",
        type: "Lunch",
        title: "Palak Paneer (Tofu Alternative)",
        desc: "Creamy spinach curry with tofu cubes, served with garlic naan.",
        cals: 600,
        protein: 25,
        carbs: 65,
        fat: 28,
        weather: ["all", "cool"],
        festivals: ["Diwali", "Holi"],
        countries: ["IN"]
    },
    {
        id: "l2",
        type: "Lunch",
        title: "Quinoa & Roasted Veggie Buddha Bowl",
        desc: "Nutrient-dense bowl with quinoa, roasted sweet potatoes, and tahini.",
        cals: 550,
        protein: 18,
        carbs: 75,
        fat: 22,
        weather: ["all"],
        festivals: [],
        countries: ["US", "CA", "UK", "AU"]
    },
    {
        id: "l3",
        type: "Lunch",
        title: "Margherita Pizza (Vegan)",
        desc: "Classic thin crust pizza with tomato sauce, vegan mozzarella, and fresh basil.",
        cals: 700,
        protein: 15,
        carbs: 90,
        fat: 25,
        weather: ["all"],
        festivals: [],
        countries: ["IT", "US", "UK", "EU"]
    },
    {
        id: "l4",
        type: "Lunch",
        title: "Spicy Black Bean & Corn Quesadillas",
        desc: "Whole wheat tortillas filled with black beans, corn, and vegan cheese with salsa.",
        cals: 650,
        protein: 24,
        carbs: 75,
        fat: 28,
        weather: ["all"],
        festivals: ["Cinco de Mayo"],
        countries: ["MX", "US", "CA"]
    },
    {
        id: "l5",
        type: "Lunch",
        title: "Chole Bhature",
        desc: "Spicy chickpea curry served with fluffy deep-fried bread.",
        cals: 800,
        protein: 20,
        carbs: 95,
        fat: 35,
        weather: ["all"],
        festivals: ["Vaisakhi"],
        countries: ["IN"]
    },
    {
        id: "l6",
        type: "Lunch",
        title: "Vegan Ploughman's Lunch",
        desc: "Crusty bread, vegan cheddar, apple, celery, and pickle relish.",
        cals: 500,
        protein: 15,
        carbs: 65,
        fat: 20,
        weather: ["warm", "cool"],
        festivals: [],
        countries: ["UK", "IE", "AU"]
    },
    {
        id: "l7",
        type: "Lunch",
        title: "Besan Chilla & Sprouted Moong Salad",
        desc: "Nutrient-dense savory chickpea pancakes served with a high-protein sprouted lentil salad.",
        cals: 450,
        protein: 26,
        carbs: 55,
        fat: 15,
        weather: ["all", "warm"],
        festivals: [],
        countries: ["IN"]
    },
    {
        id: "l8",
        type: "Lunch",
        title: "Rajma Chawal (Kidney Beans & Rice)",
        desc: "Classic North Indian comfort food: slow-cooked kidney beans in a rich tomato gravy over rice.",
        cals: 650,
        protein: 25,
        carbs: 90,
        fat: 15,
        weather: ["all", "cold"],
        festivals: [],
        countries: ["IN"]
    },
    {
        id: "l9",
        type: "Lunch",
        title: "Soya Chunk Curry & Roti",
        desc: "Extremely high protein soy chunks cooked in a spicy onion-tomato masala, served with whole wheat roti.",
        cals: 600,
        protein: 35,
        carbs: 70,
        fat: 18,
        weather: ["all"],
        festivals: [],
        countries: ["IN"]
    },
    {
        id: "l10",
        type: "Lunch",
        title: "Hidden-Veggie Mac and Cheese",
        desc: "Creamy macaroni and cheese blended with pureed cauliflower and carrots for a kid-friendly nutrient boost.",
        cals: 500,
        protein: 20,
        carbs: 65,
        fat: 18,
        weather: ["all", "cold", "cool"],
        festivals: [],
        countries: ["US", "UK", "CA", "AU", "IN", "EU"]
    },
    {
        id: "l11",
        type: "Lunch",
        title: "Mini Veggie & Cheese Quesadillas",
        desc: "Kid-sized tortillas melted with mild cheddar and finely chopped mild veggies, served with smooth salsa.",
        cals: 450,
        protein: 16,
        carbs: 45,
        fat: 22,
        weather: ["all", "warm"],
        festivals: [],
        countries: ["MX", "US", "CA", "AU", "IN"]
    },

    // DINNER
    {
        id: "d1",
        type: "Dinner",
        title: "Vegetable & Soy Chunk Biryani",
        desc: "Aromatic basmati rice cooked with mixed vegetables, high-protein soy chunks, and Indian spices.",
        cals: 680,
        protein: 26,
        carbs: 95,
        fat: 18,
        weather: ["all", "cold", "cool"],
        festivals: ["Eid", "Diwali"],
        countries: ["IN"]
    },
    {
        id: "d2",
        type: "Dinner",
        title: "Mushroom Wellington",
        desc: "Savory mushroom and spinach filling baked in golden puff pastry.",
        cals: 850,
        protein: 22,
        carbs: 85,
        fat: 48,
        weather: ["cold", "cool"],
        festivals: ["Christmas", "Thanksgiving", "New Year's Day"],
        countries: ["UK", "US", "CA"]
    },
    {
        id: "d3",
        type: "Dinner",
        title: "Pasta Primavera",
        desc: "Fettuccine tossed with seasonal spring vegetables in a light garlic oil sauce.",
        cals: 550,
        protein: 16,
        carbs: 85,
        fat: 15,
        weather: ["warm", "hot"],
        festivals: [],
        countries: ["IT", "US", "EU"]
    },
    {
        id: "d4",
        type: "Dinner",
        title: "Vegetarian Enchiladas",
        desc: "Corn tortillas stuffed with zucchini, corn, and black beans in red sauce.",
        cals: 700,
        protein: 22,
        carbs: 80,
        fat: 30,
        weather: ["all"],
        festivals: [],
        countries: ["MX", "US"]
    },
    {
        id: "d5",
        type: "Dinner",
        title: "Dal Makhani & Jeera Rice",
        desc: "Slow-cooked black lentils and kidney beans in a creamy tomato sauce with cumin rice.",
        cals: 750,
        protein: 26,
        carbs: 90,
        fat: 28,
        weather: ["cold", "cool"],
        festivals: [],
        countries: ["IN"]
    },
    {
        id: "d6",
        type: "Dinner",
        title: "Beyond Burger with Sweet Potato Fries",
        desc: "Plant-based patty with lettuce, tomato, and vegan mayo on a brioche bun.",
        cals: 800,
        protein: 30,
        carbs: 85,
        fat: 40,
        weather: ["all", "hot"],
        festivals: ["4th of July"],
        countries: ["US", "CA", "AU"]
    },
    {
        id: "d7",
        type: "Dinner",
        title: "Tofu Tikka Masala",
        desc: "Grilled tofu cubes simmered in a creamy, spiced tomato sauce.",
        cals: 620,
        protein: 28,
        carbs: 55,
        fat: 25,
        weather: ["all", "cool"],
        festivals: ["Diwali", "Holi"],
        countries: ["IN", "UK", "US"]
    },
    {
        id: "d8",
        type: "Dinner",
        title: "Matar Paneer & Quinoa",
        desc: "A healthy twist on the classic peas and paneer curry, served with high-protein quinoa.",
        cals: 580,
        protein: 30,
        carbs: 60,
        fat: 24,
        weather: ["all"],
        festivals: [],
        countries: ["IN"]
    },
    {
        id: "d9",
        type: "Dinner",
        title: "Sweet Potato & Lentil Nuggets",
        desc: "Kid-friendly baked nuggets made from sweet potatoes and lentils, served with a side of ketchup and peas.",
        cals: 450,
        protein: 18,
        carbs: 60,
        fat: 12,
        weather: ["all"],
        festivals: [],
        countries: ["US", "UK", "CA", "AU", "IN"]
    },
    {
        id: "d10",
        type: "Dinner",
        title: "Vegetarian Meatballs with Spaghetti",
        desc: "High-protein soy meatballs served over spaghetti with a mild, sweet tomato sauce.",
        cals: 550,
        protein: 25,
        carbs: 75,
        fat: 16,
        weather: ["all", "cold", "cool"],
        festivals: [],
        countries: ["IT", "US", "UK", "EU", "AU", "IN"]
    }
];
